import Provider from './Provider'
import './globals.css'

export const metadata = {
  title: 'EduConnect',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <link rel="icon" href="/EduConnectLogoSmall.ico"></link>
      <body>
        <Provider>{children}</Provider>
      </body>
    </html>
  )
}
